### ISSUE TITLE
Statues

### ISSUE THREAD

**Issue by SonicBoom213** [DivineRPG/DivineRPG#162]
It seems that, while this mod is compatible with numerous mods (I've tested 49 so far, I can provide the list if you want! :D), When using it with Nevermine, it gives me the error:

Initializing game java.lang.IllegalArgumentException: Duplicate id: Statue

I know this mod has a statue mob, but I think it's the statues from the bosses of both mods that causes the conflict? I thought that these mods were supposed to work together, so I decided to let you guys know!

**Comment by RadioactiveStud** [comment]
It's because the Statues have the exact same name probably.

**Comment by Eternaldoom** [comment]
Can you post the log?

**Comment by SonicBoom213** [comment]
Sure thing

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 2/11/15 3:19 PM
Description: Initializing game

java.lang.IllegalArgumentException: Duplicate id: Statue
	at net.minecraft.tileentity.TileEntity.func_145826_a(TileEntity.java:43)
	at cpw.mods.fml.common.registry.GameRegistry.registerTileEntity(GameRegistry.java:275)
	at net.nevermine.common.ClientProxy.RenderInformation(ClientProxy.java:41)
	at net.nevermine.common.nevermine.PreInit(nevermine.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.tileentity.TileEntity.func_145826_a(TileEntity.java:43)
	at cpw.mods.fml.common.registry.GameRegistry.registerTileEntity(GameRegistry.java:275)
	at net.nevermine.common.ClientProxy.RenderInformation(ClientProxy.java:41)
	at net.nevermine.common.nevermine.PreInit(nevermine.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_05, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 179664064 bytes (171 MB) / 451510272 bytes (430 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 Optifine OptiFine_1.7.10_HD_A4 51 mods loaded, 51 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized
	se{0.4.1} [Super Enchants] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	lucky{5.1.0} [Lucky Block] ([1-7-10]_Lucky_Block_v5-1-0.jar) Unloaded->Constructed->Pre-initialized
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized
	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) Unloaded->Constructed->Pre-initialized
	FLabsBF{4.1.2} [Better Furnaces] ([1.7.10]Better_Furnaces_V4.1.2.jar) Unloaded->Constructed->Pre-initialized
	DamageIndicatorsMod{3.2.0} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.0.jar) Unloaded->Constructed->Pre-initialized
	abyssalcraft{1.8.2} [AbyssalCraft] (AbyssalCraft-1.7.10-1.8.2.jar) Unloaded->Constructed->Pre-initialized
	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8b.jar) Unloaded->Constructed->Pre-initialized
	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized
	atum{0.6} [Atum] (Atum-1.7.10-0.6.33.jar) Unloaded->Constructed->Pre-initialized
	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) Unloaded->Constructed->Pre-initialized
	betterstorage{0.9.2.107} [BetterStorage] (Better-Storage-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	blocklings{3.0.0} [Blocklings Mod] (Blocklings-3.0.0.jar) Unloaded->Constructed->Pre-initialized
	kegare.caveworld{1.9.7} [Caveworld] (Caveworld_1.7.10-v1.9.7.jar) Unloaded->Constructed->Pre-initialized
	colourfulportalsmod{1.4.2} [Colourful Portals] (ColourfulPortals-1.4.2_for_1.7.X.jar) Unloaded->Constructed->Pre-initialized
	craftguide{1.6.8.1} [CraftGuide] (CraftGuide-1.6.8.1_1.7.2(Seems to work with 1.7.10).zip) Unloaded->Constructed->Pre-initialized
	Cyan Warrior Swords Mod{2.0} [Cyan Warrior Swords Mod] (Cyan_Warrior_Swords_Mod_2.0_for_1.7.10.jar) Unloaded->Constructed->Pre-initialized
	divinerpg{1.4.0} [DivineRPG] (Divinerpg-1.4.jar) Unloaded->Constructed->Pre-initialized
	DyeableBeds{1.7.2 R2} [Dyeable Beds] (Dyeable-Beds-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) Unloaded->Constructed->Pre-initialized
	farlanders{1.2b} [The Farlanders] (farlanders-1.7.10-v1.2b.jar) Unloaded->Constructed->Pre-initialized
	GalacticraftCore{3.0.7} [Galacticraft Core] (GalacticraftCore-1.7-3.0.7.256.jar) Unloaded->Constructed->Pre-initialized
	GalacticraftMars{3.0.7} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.7.256.jar) Unloaded->Constructed->Pre-initialized
	HardcoreEnderExpansion{1.7} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.7.jar) Unloaded->Constructed->Pre-initialized
	iChunUtil{4.1.2} [iChunUtil] (iChunUtil-4.1.2.jar) Unloaded->Constructed->Pre-initialized
	Hats{4.0.0} [Hats] (Hats-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	InfernalMobs{1.5.9} [Infernal Mobs] (InfernalMobs-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	ani_koto{v1.6} [Kingdoms of the Overworld Mod] (Kingdoms of the Overworld-1.7.10-1.6.jar) Unloaded->Constructed->Pre-initialized
	lom{1.7.10-3.0.1b} [LotsOMobs] (lom-1.7.10-3.0.2.jar) Unloaded->Constructed->Pre-initialized
	mod_cobalt{1.5.6} [CobaltMod] (mod_cobalt-1.7.10-1.5.6.jar) Unloaded->Constructed->Pre-initialized
	morehealth{6.2} [More Health Forge] (More Health Enchanted-1.7.10-6.2.zip) Unloaded->Constructed->Pre-initialized
	MoreEnchants{1.3.0} [MoreEnchants] (MoreEnchants-MC1.7-1.3.1.jar) Unloaded->Constructed->Pre-initialized
	Morph{0.9.0} [Morph] (Morph-Beta-0.9.0.jar) Unloaded->Constructed->Pre-initialized
	cfm{3.4.5} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.5(1.7.10).jar) Unloaded->Constructed->Pre-initialized
	mwaw{1.7.10-0.0.4} [Elemental Witch Mod] (mwaw-1.7.10-0.0.4.jar) Unloaded->Constructed->Pre-initialized
	nevermine{1.1.1} [Nevermine] (nevermine-1.1.6H.jar) Unloaded->Constructed->Errored
	pandorasbox{2.0.1} [Pandora's Box] (PandorasBox-2.0.1.jar) Unloaded->Constructed->Pre-initialized
	runicdungeons{0.9.4} [Runic Dungeons] (runicdungeons-0.9.4.jar) Unloaded->Constructed->Pre-initialized
	ashjacksimukraftreloaded{1.0.1d} [Sim-U-Kraft Reloaded] (simukraft-1.7.10-1.0.1d.jar) Unloaded->Constructed->Pre-initialized
	RioV{v2.4.9} [The Mists of RioV] (The Mists of RioV - v2.4.9.jar) Unloaded->Constructed->Pre-initialized
	erebus{0.2a} [Erebus] (TheErebus-0.2a.jar) Unloaded->Constructed->Pre-initialized
	kitchen{1.3.6} [The Kitchen Mod] (TheKitchenMod-1.3.6-1.7.2-10.jar) Unloaded->Constructed->Pre-initialized
	toolsdoneright{1.1.4} [Tools Done Right] (Tools Done Right by NukeDuck [1.7.10][1.1.4].zip) Unloaded->Constructed->Pre-initialized
	TwilightForest{2.3.2} [The Twilight Forest] (twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized
	nolpfij_wildycraft{1.7.3} [Wildycraft] (wildycraft-1.7.10-1.7.3.jar) Unloaded->Constructed->Pre-initialized
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.3304, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Eternaldoom** [comment]
Ok yeah it was a TileEntity conflict.
