### ISSUE TITLE
DataWatcher ID conflict with Nevermine 

### ISSUE THREAD

**Issue by SonicBoom213** [DivineRPG/DivineRPG#164]
Thanks again for the previous fix! Hopefully this will be the last time I bother you guys!

When I tried creating a new world for Nevermine and Divine RPG, I get the following error. I'm not sure what's causing it.

---- Minecraft Crash Report ----
Description: Ticking memory connection

java.lang.IllegalArgumentException: Duplicate id value for 27!
	at net.minecraft.entity.DataWatcher.func_75682_a(SourceFile:64)
	at net.nevermine.bar.energyHelper.<init>(energyHelper.java:26)
	at net.nevermine.bar.energyHelper.addProperties(energyHelper.java:40)
	at net.nevermine.bar.EntityConstructorEvent.onEntityConstructing(EntityConstructorEvent.java:12)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_36_EntityConstructorEvent_onEntityConstructing_EntityConstructing.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.entity.Entity.<init>(Entity.java:179)
	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:119)
	at net.minecraft.entity.player.EntityPlayer.<init>(EntityPlayer.java:141)
	at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:138)
	at net.minecraft.server.management.ServerConfigurationManager.func_148545_a(ServerConfigurationManager.java:397)
	at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:101)
	at net.minecraft.server.network.NetHandlerLoginServer.func_147233_a(NetHandlerLoginServer.java:60)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:215)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.entity.DataWatcher.func_75682_a(SourceFile:64)
	at net.nevermine.bar.energyHelper.<init>(energyHelper.java:26)
	at net.nevermine.bar.energyHelper.addProperties(energyHelper.java:40)
	at net.nevermine.bar.EntityConstructorEvent.onEntityConstructing(EntityConstructorEvent.java:12)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_36_EntityConstructorEvent_onEntityConstructing_EntityConstructing.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.entity.Entity.<init>(Entity.java:179)
	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:119)
	at net.minecraft.entity.player.EntityPlayer.<init>(EntityPlayer.java:141)
	at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:138)
	at net.minecraft.server.management.ServerConfigurationManager.func_148545_a(ServerConfigurationManager.java:397)
	at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:101)
	at net.minecraft.server.network.NetHandlerLoginServer.func_147233_a(NetHandlerLoginServer.java:60)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:215)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@2c93e35d
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_05, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 151227336 bytes (144 MB) / 535375872 bytes (510 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 12 mods loaded, 12 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1230} [Forge Mod Loader] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1230} [Minecraft Forge] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	matacraft{1.0} [MataCraft] ([1.7.10-10.13.2.1230]MataCraft-1.7.10-1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DamageIndicatorsMod{3.2.0} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	colourfulportalsmod{1.4.2} [Colourful Portals] (ColourfulPortals-1.4.2_for_1.7.X.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	craftguide{1.6.8.1} [CraftGuide] (CraftGuide-1.6.8.1_1.7.2(Seems to work with 1.7.10).zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	divinerpg{1.4.0} [DivineRPG] (Divinerpg-1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DyeableBeds{1.7.2 R2} [Dyeable Beds] (Dyeable-Beds-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	nevermine{1.1.1} [Nevermine] (nevermine-1.1.6H.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by krwminer** [comment]
This looks like a Datawatcher ID conflict. DivineRPG uses 27 and 28 for the AracanaBar.
To fix it for now, there is a config file option to change the Datawatcher IDs for Nevermine.

We might still adjust the default values we are using and/or make it a config file option also.

**Comment by SonicBoom213** [comment]
Wow, thanks again! I switched the DataWatcher ID's and everything works fine!

**Comment by krwminer** [comment]
I think we should change the default IDs and add a config file option for these, since it is such a limited resource.
