### ISSUE TITLE
Mod will not run in obfuscated environment

### ISSUE THREAD

**Issue by gamrguy** [DivineRPG/DivineRPG#203]
Using Forge 1291, minecraft 1.7.10, and no mods other than Divine RPG, I always get this error when running in an obfuscated environment (a fresh Forge install):
```
cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: net.divinerpg.items.base.ItemModFood.setCreativeTab(Lnet/minecraft/creativetab/CreativeTabs;)Lnet/minecraft/item/Item;
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
Apparently DRPG is failing to properly access the base Item class, though it works perfectly 100% of the time in the deobfuscated (dev) environment with the same forge/minecraft versions.

**Comment by Eternaldoom** [comment]
Are you sure you built it correctly? I have definitely been able to run it in an obfuscated environment.

**Comment by gamrguy** [comment]
Here's the steps I took:
1. Set up the Forge dev environment with the DRPG source code
2. Press the build button in Eclipse
3. Minecraft runs fine
4. Compress the files in the bin folder into a .zip file
5. Use it in obfuscated environment
If there's something else please let me know.

**Comment by Eternaldoom** [comment]
The files in the bin folder are deobfuscated. If you've never built a mod before you shouldn't be trying to test DRPG.

**Comment by gamrguy** [comment]
Well, those files are .class files, so I assumed those were properly 'built' files. And yes, I'll be honest, I've never actually built a mod, and I'm really only trying this for my own purposes - mostly analyzing the code so I'll know what I'm doing if I decide to actually build my own mod someday.
