### ISSUE TITLE
Server closes

### ISSUE THREAD

**Issue by ShadowOfStrelok** [DivineRPG/DivineRPG#374]
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 30.10.16 3:26
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
    at net.divinerpg.entities.vanilla.EntityAyeracoPurple.func_70109_d(EntityAyeracoPurple.java:96)
    at net.minecraftforge.cauldron.CauldronHooks.checkBoundingBoxSize(CauldronHooks.java:174)
    at net.minecraft.world.World.func_72945_a(World.java:1913)
    at net.minecraft.entity.Entity.func_70091_d(Entity.java:739)
    at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1776)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2108)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:388)
    at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:36)
    at net.divinerpg.entities.vanilla.EntityAyeraco.func_70636_d(EntityAyeraco.java:69)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1899)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:213)
    at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:41)
    at net.divinerpg.entities.vanilla.EntityAyeraco.func_70071_h_(EntityAyeraco.java:89)
    at net.divinerpg.entities.vanilla.EntityAyeracoPurple.func_70071_h_(EntityAyeracoPurple.java:61)
    at net.minecraft.world.World.func_72866_a(World.java:2674)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:800)
    at net.minecraft.world.World.func_72870_g(World.java:2623)
    at net.minecraft.world.World.func_72939_s(World.java:2423)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:633)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.divinerpg.entities.vanilla.EntityAyeracoPurple.func_70109_d(EntityAyeracoPurple.java:96)
    at net.minecraftforge.cauldron.CauldronHooks.checkBoundingBoxSize(CauldronHooks.java:174)
    at net.minecraft.world.World.func_72945_a(World.java:1913)
    at net.minecraft.entity.Entity.func_70091_d(Entity.java:739)
    at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1776)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2108)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:388)
    at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:36)
    at net.divinerpg.entities.vanilla.EntityAyeraco.func_70636_d(EntityAyeraco.java:69)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1899)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:213)
    at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:41)
    at net.divinerpg.entities.vanilla.EntityAyeraco.func_70071_h_(EntityAyeraco.java:89)
    at net.divinerpg.entities.vanilla.EntityAyeracoPurple.func_70071_h_(EntityAyeracoPurple.java:61)
    at net.minecraft.world.World.func_72866_a(World.java:2674)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:800)
    at net.minecraft.world.World.func_72870_g(World.java:2623)

-- Entity being ticked --
Details:
    Entity Type: DRPGAyeracoPurple (net.divinerpg.entities.vanilla.EntityAyeracoPurple)
    Entity ID: 74590
    Entity Name: Ayeraco Purple
    Entity's Exact location: 403,59, 73,00, 417,67
    Entity's Block location: World: (403,73,417), Chunk: (at 3,4,1 in 25,26; contains blocks 400,0,416 to 415,255,431), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Entity's Momentum: 3,90, 20,00, 3,90
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2423)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:633)

-- Affected level --
Details:
    Level name: arena
    All players: 2 total; [EntityPlayerMP['Strelok'/30891, l='arena', x=402,25, y=72,00, z=415,66](Strelok at 402.2479697752827,72.0,415.6637920471638), EntityPlayerMP['Asakura999'/30966, l='arena', x=133,00, y=64,00, z=106,00](Asakura999 at 133.0,64.0,106.0)]
    Chunk stats: ServerChunkCache: 874 Drop: 0
    Level seed: -6021701233626025830
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (133,64,106), Chunk: (at 5,4,10 in 8,6; contains blocks 128,0,96 to 143,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 231497 game time, 231497 day time
    Level dimension: 3
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 54219 (now: false), thunder time: 29470 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    KCauldron Version: pw.prok:KCauldron:1.7.10-1614.201 Official
    Plugins: AsyncWorldEditInjector, MultiWorld, WorldEdit, AsyncWorldEdit
    Disabled Plugins: 
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 431931376 bytes (411 MB) / 1623236608 bytes (1548 MB) up to 2077753344 bytes (1981 MB)
    JVM Flags: 3 total; -Xincgc -Xmx2048M -XX:MaxPermSize=512m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 3, tcache: 0, allocated: 12, tallocated: 96
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 24 mods loaded, 24 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](KCauldron-1.7.10-1614.201.jar) 
    UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge](KCauldron-1.7.10-1614.201.jar) 
    UCHIJAAAA   kimagine{0.2} [KImagine](minecraft.jar) 
    UCHIJAAAA   BinniePatcher{1.8.2} [Binnie Patcher](minecraft.jar) 
    UCHIJAAAA   BuildCraft|Core{7.1.18} [BuildCraft](buildcraft-7.1.18.jar) 
    UCHIJAAAA   BuildCraft|Transport{7.1.18} [BC Transport](buildcraft-7.1.18.jar) 
    UCHIJAAAA   BuildCraft|Silicon{7.1.18} [BC Silicon](buildcraft-7.1.18.jar) 
    UCHIJAAAA   BuildCraft|Factory{7.1.18} [BC Factory](buildcraft-7.1.18.jar) 
    UCHIJAAAA   additionalpipes{4.7.0} [Additional Pipes](additionalpipes-4.7.2.jar) 
    UCHIJAAAA   IC2{2.2.826-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.826-experimental.jar) 
    UCHIJAAAA   Forestry{4.2.16.64} [Forestry for Minecraft](forestry_1.7.10-4.2.16.64.jar) 
    UCHIJAAAA   BinnieCore{2.0-pre14} [Binnie Core](binnie-mods-2.0-pre14.jar) 
    UCHIJAAAA   Botany{2.0-pre14} [Botany](binnie-mods-2.0-pre14.jar) 
    UCHIJAAAA   ExtraBees{2.0-pre14} [Extra Bees](binnie-mods-2.0-pre14.jar) 
    UCHIJAAAA   ExtraTrees{2.0-pre14} [Extra Trees](binnie-mods-2.0-pre14.jar) 
    UCHIJAAAA   Genetics{2.0-pre14} [Genetics](binnie-mods-2.0-pre14.jar) 
    UCHIJAAAA   BuildCraft|Energy{7.1.18} [BC Energy](buildcraft-7.1.18.jar) 
    UCHIJAAAA   BuildCraft|Builders{7.1.18} [BC Builders](buildcraft-7.1.18.jar) 
    UCHIJAAAA   BuildCraft|Robotics{7.1.18} [BC Robotics](buildcraft-7.1.18.jar) 
    UCHIJAAAA   CompactSolars{4.4.41.316} [Compact Solar Arrays](CompactSolars-1.7.10-4.4.41.316-universal.jar) 
    UCHIJAAAA   customnpcs{1.7.10d} [CustomNpcs](CustomNPCs_1.7.10d%2821feb16%29.jar) 
    UCHIJAAAA   divinerpg{1.4.0.5} [DivineRPG](DivineRPG.jar) 
    UCHIJAAAA   Railcraft{9.12.2.0} [Railcraft](Railcraft_1.7.10-9.12.2.0.jar) 
    Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Bukkit, Cauldron, or other Bukkit replacement
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
Info: The following plugins have been disabled in the config: storage, agricraft, biomesoplenty, chisel, extrautilities, harvestcraft, magicalcrops, natura, plantmegapack, witchery
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 2 / 20; [EntityPlayerMP['Strelok'/30891, l='arena', x=402,25, y=72,00, z=415,66](Strelok at 402.2479697752827,72.0,415.6637920471638), EntityPlayerMP['Asakura999'/30966, l='arena', x=133,00, y=64,00, z=106,00](Asakura999 at 133.0,64.0,106.0)]
    Is Modded: Definitely; Server brand changed to 'kcauldron,cauldron,craftbukkit,mcpc,fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by Eternaldoom** [comment]
KCauldron isn't supported by us.
