### ISSUE TITLE
Datawatch id conflict with balkon's weapon mod

### ISSUE THREAD

**Issue by Sulferix** [DivineRPG/DivineRPG#380]
same as this issue: https://github.com/DivineRPG/DivineRPG/issues/164 but with the ballon's weapon mod.... looking at those comment though, i have no clue how to 'switch datawatch ids' if anyone could point me in the right direction or allow the config to define the ids that'd be great. been at this garbage all night. tired of having to waste days at a time installing mods into this blasted game.

here is my error message for the record: 
---- Minecraft Crash Report ----
// Why did you do that?

Time: 6/20/17 12:57 AM
Description: Ticking memory connection

java.lang.IllegalArgumentException: Duplicate id value for 27!
	at net.minecraft.entity.DataWatcher.func_75682_a(SourceFile:64)
	at ckathode.weaponmod.PlayerWeaponData.initPlayerWeaponData(PlayerWeaponData.java:33)
	at ckathode.weaponmod.WMCommonEventHandler.onEntityConstructed(WMCommonEventHandler.java:14)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_122_WMCommonEventHandler_onEntityConstructed_EntityConstructing.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.entity.Entity.<init>(Entity.java:179)
	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:119)
	at net.minecraft.entity.player.EntityPlayer.<init>(EntityPlayer.java:141)
	at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:138)
	at net.minecraft.server.management.ServerConfigurationManager.func_148545_a(ServerConfigurationManager.java:410)
	at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:101)
	at net.minecraft.server.network.NetHandlerLoginServer.func_147233_a(NetHandlerLoginServer.java:60)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:215)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.entity.DataWatcher.func_75682_a(SourceFile:64)
	at ckathode.weaponmod.PlayerWeaponData.initPlayerWeaponData(PlayerWeaponData.java:33)
	at ckathode.weaponmod.WMCommonEventHandler.onEntityConstructed(WMCommonEventHandler.java:14)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_122_WMCommonEventHandler_onEntityConstructed_EntityConstructing.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.entity.Entity.<init>(Entity.java:179)
	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:119)
	at net.minecraft.entity.player.EntityPlayer.<init>(EntityPlayer.java:141)
	at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:138)
	at net.minecraft.server.management.ServerConfigurationManager.func_148545_a(ServerConfigurationManager.java:410)
	at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:101)
	at net.minecraft.server.network.NetHandlerLoginServer.func_147233_a(NetHandlerLoginServer.java:60)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:215)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@32cf76a0
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.10.5
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 128070736 bytes (122 MB) / 479633408 bytes (457 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	antiidconflict{1.3.5} [Anti Id Conflict] (AntiIdConflict-LATEST-1.7.10.jar) 
	UCHIJAAAA	nevermine{2.3} [AdventOfAscension] (AoA-2.4.B.jar) 
	UCHIJAAAA	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Eternaldoom** [comment]
You aren't even using our mod.... And AoA's datawatcher values are configurable IIRC.
