### ISSUE TITLE
crash when generating new world

### ISSUE THREAD

**Issue by Saftsalat1234** [DivineRPG/DivineRPG#434]
how do i fix this?
system: windows10/rtx3070/ryzen7/32gb of ram.
i have 50 other mods installed, but if i try to remove them, i have the same error and its crashing.
here is my error:

19:12:31.848
Unreported exception thrown!
java.lang.NullPointerException
	at net.divinerpg.utils.events.UpdateChecker.isUpdateAvailable(UpdateChecker.java:25)
	at net.divinerpg.client.render.gui.GUIOverlay.drawOverlay(GUIOverlay.java:36)
	at net.divinerpg.utils.events.EventOverlay.renderOverlay(EventOverlay.java:19)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_72_EventOverlay_renderOverlay_RenderGameOverlayEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:899)
	at net.minecraftforge.client.GuiIngameForge.renderExperience(GuiIngameForge.java:544)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:150)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1327)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
19:12:32.535
Process crashed with exit code -1

**Comment by NicosaurusRex99** [comment]
This looks like 1.7.10. Bit of luck you can just disable the update checker in the config file

**Comment by Saftsalat1234** [comment]
> This looks like 1.7.10. Bit of luck you can just disable the update checker in the config file

thanks!
where is the config?

**Comment by NicosaurusRex99** [comment]
So goto mods folder. go back a layer to where you can see resourcepacks/mods/config folders.
choose config. Maybe something called DivineRPG.cfg or something similar

**Comment by Saftsalat1234** [comment]
thanks, but it didnt work :/

Unreported exception thrown!
java.lang.NullPointerException
	at net.divinerpg.utils.events.UpdateChecker.isUpdateAvailable(UpdateChecker.java:25)
	at net.divinerpg.client.render.gui.GUIOverlay.drawOverlay(GUIOverlay.java:34)
	at net.divinerpg.utils.events.EventOverlay.renderOverlay(EventOverlay.java:19)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_72_EventOverlay_renderOverlay_RenderGameOverlayEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:899)
	at net.minecraftforge.client.GuiIngameForge.renderExperience(GuiIngameForge.java:544)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:150)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1327)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
19:36:07.362
Process crashed with exit code -1

**Comment by Saftsalat1234** [comment]
i have the same error again, and again, and again :(

**Comment by NicosaurusRex99** [comment]
1.7.10 is unsupported so we can't do much
