### ISSUE TITLE
Divine RPG crashes, Mod file for Server?

### ISSUE THREAD

**Issue by DieIntelligenz** [DivineRPG/DivineRPG#436]
Hello everbody,
I have a Minecraft Nitrado Server and installed Divine RPG on it but when I log on to the server my game crashes instanly
Here is what it says after crashing: 
The game crashed whilst ticking screen
Error: java.lang.IndexOutOfBoundsException
Exit-Code: -1
Could it be that I need a Mod Server File and if yes can somebody send me the link for it 

Thanks for your help!
Best wishes Die_Intelligenz

By the way this is the full crash report:

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 28.07.21 17:37
Description: Ticking screen

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:253)
	at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:350)
	at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2216)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:240)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:253)
	at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:350)
	at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2216)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:240)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.multiplayer.GuiConnecting

-- Affected level --
Details:
	Level name: MpServer
	All players: 0 total; []
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 0 total; []
	Retry entities: 0 total; []
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 270943608 bytes (258 MB) / 570425344 bytes (544 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	divinerpg{1.4.1.3} [DivineRPG] (DivineRPG-Mod-1.7.10.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 466.63' Renderer: 'NVIDIA GeForce RTX 2070/PCIe/SSE2'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce RTX 2070/PCIe/SSE2 GL version 4.6.0 NVIDIA 466.63, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Magma 32x.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by NicosaurusRex99** [comment]
1.7.10 isn't supported. Are you maybe using a cracked launcher or some form of weird server wrapper?

**Comment by DieIntelligenz** [comment]
So 1.7.10 is not able to use for a server?
What do you mean with cracked launcher...
I´m renting the server from nitrado as a little info.

**Comment by NicosaurusRex99** [comment]
Did you pay for Minecraft. Do you launch with forge, sponge, bukkit some other util

**Comment by DieIntelligenz** [comment]
yes of course i bought Minecraft. I launch Minecraft with Forge...

**Comment by DieIntelligenz** [comment]
So I wanted to play Divine RPG with my friends because I saw  the Mod on Youtube and the Youtuber also played it with a friend so I thought it should work...
Just a little info and thanks for your help and time!

**Comment by NicosaurusRex99** [comment]
I know the 1.12.2 should run on a server. But the issue looks to me like a bug with the multiplayer button but I'm not overly familiar with 1.7.10

**Comment by DieIntelligenz** [comment]
oh ok than I will try the 1.12.2 version and if its still not working I´ll let you know...

**Comment by DieIntelligenz** [comment]
So I tried and it works now thank you so much for your help and time 
Best wishes 
Die_Intelligenz
