### ISSUE TITLE
SERVER compatiblility

### ISSUE THREAD

**Issue by dutchblizzard** [DivineRPG/DivineRPG#468]
i was making a mod pack around you amzing mod i played since minecraft 1.4.7 but the lastest version ([DivineRPG-1.8.5.jar](https://www.curseforge.com/minecraft/mc-mods/official-divinerpg/files/3641130)) is not  server compatible. it cause the badly compressed packet error.

could you plz lookin to that for me, and patch it.

so i finaly can use it agian in the mod pack

**Comment by Locomenmod** [comment]
Everything works for me, please send logs and more details.

**Comment by dutchblizzard** [comment]
[Wasn't really sure what log of my logs contained it so i added all of today,](https://mega.nz/file/SYVB0ALJ#Gg8P3LqOUVdo0zez_NCPTdDja9nB07xjDukHnnVAIrg)

**Comment by NicosaurusRex99** [comment]
Im seeing a few errors here. 1 being `FATAL`
here are some of the errors you could maybe fix via data packs
```[20:05:11] [Netty Client IO #6/ERROR]: Error adding element: Unknown registry element mod.beethoven92.betterendforge.common.world.feature.SinglePlantFeature@2cfea18e
[20:05:11] [Netty Client IO #6/ERROR]: Error adding element: Base value out of range: 256 [-10-128]
[20:05:12] [Netty Client IO #6/ERROR]: Feature: Not a JSON object: "minecraft:seagrass_simple"
[20:05:12] [Netty Client IO #6/ERROR]: Feature: Not a JSON object: "minecraft:red_mushroom_taiga"; Not a JSON object: "minecraft:brown_mushroom_taiga"; Not a JSON object: "minecraft:patch_grass_taiga_2"; Not a JSON object: "minecraft:patch_large_fern"
[20:05:14] [Netty Client IO #6/ERROR]: Could not deserialize minecraft:
[20:05:14] [Netty Client IO #6/ERROR]: Could not deserialize minecraft:
[20:05:14] [Netty Client IO #6/ERROR]: Could not deserialize minecraft:
[20:05:14] [Netty Client IO #6/ERROR]: Could not deserialize minecraft:
```
but the `packet_handler` issue will need a bit more time to figure out stuff. i dont think its caused by divine because our packet handler is called `divine_packet`


```
[19:53:53] [main/FATAL]: Error executing task on Client
java.util.NoSuchElementException: packet_handler
    at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1119) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
    at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:260) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
    at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:249) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
    at net.minecraftforge.network.NetworkFilters.lambda$injectIfNecessary$1(NetworkFilters.java:48) ~[?:?]
    at net.minecraftforge.network.NetworkFilters$$Lambda$45057/1920407442.accept(Unknown Source) ~[?:?]
    at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:146) ~[guava-21.0.jar:?]
    at net.minecraftforge.network.NetworkFilters.injectIfNecessary(NetworkFilters.java:44) ~[?:?]
    at net.minecraftforge.fml.network.NetworkHooks.sendMCRegistryPackets(NetworkHooks.java:121) ~[?:?]
    at net.minecraft.client.network.play.ClientPlayNetHandler.func_147282_a(ClientPlayNetHandler.java:399) ~[?:?]
    at net.minecraft.network.play.server.SJoinGamePacket.func_148833_a(SourceFile:110) ~[?:?]
    at net.minecraft.network.play.server.SJoinGamePacket.func_148833_a(SourceFile:18) ~[?:?]
    at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
    at net.minecraft.network.PacketThreadUtil$$Lambda$44812/1942841808.run(Unknown Source) ~[?:?]
    at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
    at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
    at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
    at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
    at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:948) [?:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
    at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
    at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.28.jar:36.2]
    at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$503/2069466373.call(Unknown Source) [forge-1.16.5-36.2.28.jar:36.2]
    at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
    at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
    at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
    at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
    at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] 
```
`packet_handler`

**Comment by dutchblizzard** [comment]
okay , but wanna mention again only when i add back Divine RPG that when the badly compressed packet error and also only when joining a server world not a private world. already checked with the host and defenly not something with the server

**Comment by NicosaurusRex99** [comment]
is there a debug log?

**Comment by dutchblizzard** [comment]
[here are all the log files of the same day from the server](https://mega.nz/file/yIESmRJL#okmcI4ZnJUgCTI3j1Gy3TRu7iWmKImMN_fg8tifznQY)

**Comment by NicosaurusRex99** [comment]
Have you since installed [mantle version 1.6.152](https://www.curseforge.com/minecraft/mc-mods/mantle/files/3576386) or [above](https://www.curseforge.com/minecraft/mc-mods/mantle/files/3631982)? 
```[15Feb2022 20:29:20.703] [main/FATAL] [net.minecraftforge.fml.server.ServerModLoader/]: Crash report saved to ./crash-reports/crash-2022-02-15_20.29.20-fml.txt
[15Feb2022 20:29:20.705] [main/FATAL] [net.minecraft.server.Main/]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Mod ?etconstruct?r requires ?6mantle?r ?o1.6.152 or above?r
?7Currently, ?6mantle?r?7 is ?o?nnot installed
]
```

**Comment by dutchblizzard** [comment]
aah that the log i was trouble shooting but yes i have. 
in that log i forgot to at it back in

**Comment by NicosaurusRex99** [comment]
So does the issue still persist?

**Comment by dutchblizzard** [comment]
when i put divine RPG back in the mod pack it does

**Comment by dutchblizzard** [comment]
the wierd thing is its not the first login to the server thats a problem joining back in ( second time joining) what has the error message poppin. when i have divine rpg in the pack

**Comment by NicosaurusRex99** [comment]
im thinking if anything its the getter for the arcana system

**Comment by dutchblizzard** [comment]
link to my mod pack: https://www.curseforge.com/minecraft/modpacks/tbfl-smp/files. 
and try it out yourself,  the version that are up now don't contain divine rpg, so you gotta manually add divine rpg to it again to try it out and see for your self

**Comment by NicosaurusRex99** [comment]
Why im confused is i can join a server over and over no issues. so i think its an interaction between some mods. but ill have to do more trouble shooting after work

**Comment by dutchblizzard** [comment]
okay np
thanks already doing the effort

**Comment by NicosaurusRex99** [comment]
Your pack has issues 
```
[18Feb2022 14:50:13.066] [main/FATAL] [net.minecraftforge.fml.server.ServerModLoader/]: Crash report saved to .\crash-reports\crash-2022-02-18_14.50.13-fml.txt
[18Feb2022 14:50:13.086] [main/FATAL] [net.minecraft.server.Main/]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	TRansliterationLib Mod (transliterationlib) has failed to load correctly
§7java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/RenderType for invalid dist DEDICATED_SERVER,
	EntityCulling (entityculling) has failed to load correctly
§7java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
]
```
you will need to rework your pack

**Comment by dutchblizzard** [comment]
yeah there are 4 mods that only be client  side only mods so the can't be in de server files: BetterF3, entityculling, notenoughanimations and TRansliterationLib

**Comment by NicosaurusRex99** [comment]
326 mods O.o

**Comment by NicosaurusRex99** [comment]
Even with those 4 mods removed the server doesnt want to stay online without DivineRPG as is

**Comment by dutchblizzard** [comment]
wierd for me does

**Comment by dutchblizzard** [comment]
[latest.log](https://github.com/DivineRPG/DivineRPG/files/8095085/latest.log)
[2022-02-18-2.log](https://github.com/DivineRPG/DivineRPG/files/8095090/2022-02-18-2.log)
[2022-02-18-1.log](https://github.com/DivineRPG/DivineRPG/files/8095091/2022-02-18-1.log)

**Comment by NicosaurusRex99** [comment]
I have reproduced it. 
Please read this reddit thread
[Reddit](https://www.reddit.com/r/admincraft/comments/8yz0xw/badly_compressed_packet_issues/)
basically you need to tweak your `server.properties`
![image](https://user-images.githubusercontent.com/11579935/154640270-b8f07a18-b10e-47c3-afb8-0323c50e9997.png)
