### ISSUE TITLE
Cannot get property IntegerProperty in divinerpg:moonbulb_plant

### ISSUE THREAD

**Issue by DenisNovac** [DivineRPG/DivineRPG#534]
**Minecraft version**
1.9.2

**DivineRPG version**
1.9.6.2

**Describe the bug**
Crashes the server completely

```
[27нояб.2022 17:11:37.419] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:870) ~[server-1.19.2-20220805.130853-srg.jar%23124!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23124!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23124!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23124!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23124!/:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalArgumentException: Cannot get property IntegerProperty{name=age, clazz=class java.lang.Integer, values=[0, 1, 2]} as it does not exist in Block{divinerpg:moonbulb_plant}
	at net.minecraft.world.level.block.state.StateHolder.m_61143_(StateHolder.java:98) ~[server-1.19.2-20220805.130853-srg.jar%23124!/:?]
	at divinerpg.blocks.base.BlockModDoubleCrop.m_6861_(BlockModDoubleCrop.java:119) ~[DivineRPG-1.9.6.2.jar%23103!/:1.9.6.2]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60690_(BlockBehaviour.java:659) ~[server-1.19.2-20220805.130853-srg.jar%23124!/:?]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater$MultiNeighborUpdate.m_213563_(CollectingNeighborUpdater.java:132) ~[server-1.19.2-20220805.130853-srg.jar%23124!/:?]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.m_230645_(CollectingNeighborUpdater.java:78) ~[server-1.19.2-20220805.130853-srg.jar%23124!/:?]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.m_230660_(CollectingNeighborUpdater.java:65) ~[server-1.19.2-20220805.130853-srg.jar%23124!/:?]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.m_213547_(CollectingNeighborUpdater.java:32) ~[server-1.19.2-20220805.130853-srg.jar%23124!/:?]
	at net.minecraft.world.level.Level.m_213683_(Level.java:326) ~[server-1.19.2-20220805.130853-srg.jar%23124!/:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60705_(BlockBehaviour.java:672) ~[server-1.19.2-20220805.130853-srg.jar%23124!/:?]
	at net.minecraft.world.level.Level.markAndNotifyBlock(Level.java:257) ~[server-1.19.2-20220805.130853-srg.jar%23124!/:?]
	at net.minecraft.world.level.Level.m_6933_(Level.java:224) ~[server-1.19.2-20220805.130853-srg.jar%23124!/:?]
	at net.minecraft.world.level.Level.m_7731_(Level.java:188) ~[server-1.19.2-20220805.130853-srg.jar%23124!/:?]
	at divinerpg.blocks.base.BlockModDoubleCrop.m_213898_(BlockModDoubleCrop.java:61) ~[DivineRPG-1.9.6.2.jar%23103!/:1.9.6.2]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_222972_(BlockBehaviour.java:698) ~[server-1.19.2-20220805.130853-srg.jar%23124!/:?]
	at net.minecraft.server.level.ServerLevel.m_8714_(ServerLevel.java:446) ~[server-1.19.2-20220805.130853-srg.jar%23124!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:360) ~[server-1.19.2-20220805.130853-srg.jar%23124!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:310) ~[server-1.19.2-20220805.130853-srg.jar%23124!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:285) ~[server-1.19.2-20220805.130853-srg.jar%23124!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23124!/:?]
```

**To reproduce**
Happens randomly, perhaps somewhere in world something spawns

**Expected behavior**
Should not crash

[crash-2022-11-27_17.11.37-server.txt](https://github.com/DivineRPG/DivineRPG/files/10098405/crash-2022-11-27_17.11.37-server.txt)

**Comment by NicosaurusRex99** [comment]
we believe this is fixed and should be patched in the next update which is soon™ to come
