### ISSUE TITLE
Cannot load game after upgrade DivineRPG-1.10.6.jar  -> DivineRPG-1.10.6.1.jar 

### ISSUE THREAD

**Issue by uhloin** [DivineRPG/DivineRPG#608]
Minecraft cannot load game saved in 1.10.6 after upgrade to 1.10.6.1
Log:

[18:59:55] [Render thread/WARN] [minecraft/WorldOpenFlows]: Failed to load level data or datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.RuntimeException: No key preset in MapLike[{biomes:[{biome:"divinerpg:frozen_peaks",parameters:{continentalness:0.8f,depth:-0.2f,erosion:-0.2f,humidity:-0.2f,offset:0.0f,temperature:-0.6f,weirdness:-0.6f}},{biome:"divinerpg:snowy_peaks",parameters:{continentalness:1.0f,depth:-0.1f,erosion:-0.1f,humidity:-0.1f,offset:0.0f,temperature:0.6f,weirdness:0.0f}},{biome:"divinerpg:taiga",parameters:{continentalness:0.6f,depth:0.43f,erosion:0.43f,humidity:0.43f,offset:0.0f,temperature:0.6f,weirdness:0.0f}},{biome:"divinerpg:ice_spikes",parameters:{continentalness:0.1f,depth:0.49f,erosion:0.49f,humidity:0.49f,offset:0.3f,temperature:-0.8f,weirdness:0.6f}},{biome:"divinerpg:tundra",parameters:{continentalness:0.2f,depth:0.48f,erosion:0.48f,humidity:0.48f,offset:0.1f,temperature:0.1f,weirdness:-0.2f}},{biome:"divinerpg:frozen_ocean",parameters:{continentalness:-0.35f,depth:0.6f,erosion:0.6f,humidity:0.6f,offset:0.0f,temperature:0.0f,weirdness:0.0f}},{biome:"divinerpg:deep_frozen_ocean",parameters:{continentalness:-0.5f,depth:0.6f,erosion:0.6f,humidity:0.6f,offset:0.0f,temperature:0.0f,weirdness:0.0f}},{biome:"divinerpg:thermal_vents",parameters:{continentalness:-0.87f,depth:0.85f,erosion:0.85f,humidity:0.85f,offset:0.0f,temperature:0.1f,weirdness:0.0f}},{biome:"divinerpg:boneyard",parameters:{continentalness:-0.75f,depth:0.68f,erosion:0.68f,humidity:0.68f,offset:0.0f,temperature:-0.22f,weirdness:0.2f}}],type:"minecraft:multi_noise"}] missed input: {"divinerpg:iceika":{generator:{biome_source:{biomes:[{biome:"divinerpg:frozen_peaks",parameters:{continentalness:0.8f,depth:-0.2f,erosion:-0.2f,humidity:-0.2f,offset:0.0f,temperature:-0.6f,weirdness:-0.6f}},{biome:"divinerpg:snowy_peaks",parameters:{continentalness:1.0f,depth:-0.1f,erosion:-0.1f,humidity:-0.1f,offset:0.0f,temperature:0.6f,weirdness:0.0f}},{biome:"divinerpg:taiga",parameters:{continentalness:0.6f,depth:0.43f,erosion:0.43f,humidity:0.43f,offset:0.0f,temperature:0.6f,weirdness:0.0f}},{biome:"divinerpg:ice_spikes",parameters:{continentalness:0.1f,depth:0.49f,erosion:0.49f,humidity:0.49f,offset:0.3f,temperature:-0.8f,weirdness:0.6f}},{biome:"divinerpg:tundra",parameters:{continentalness:0.2f,depth:0.48f,erosion:0.48f,humidity:0.48f,offset:0.1f,temperature:0.1f,weirdness:-0.2f}},{biome:"divinerpg:frozen_ocean",parameters:{continentalness:-0.35f,depth:0.6f,erosion:0.6f,humidity:0.6f,offset:0.0f,temperature:0.0f,weirdness:0.0f}},{biome:"divinerpg:deep_frozen_ocean",parameters:{continentalness:-0.5f,depth:0.6f,erosion:0.6f,humidity:0.6f,offset:0.0f,temperature:0.0f,weirdness:0.0f}},{biome:"divinerpg:thermal_vents",parameters:{continentalness:-0.87f,depth:0.85f,erosion:0.85f,humidity:0.85f,offset:0.0f,temperature:0.1f,weirdness:0.0f}},{biome:"divinerpg:boneyard",parameters:{continentalness:-0.75f,depth:0.68f,erosion:0.68f,humidity:0.68f,offset:0.0f,temperature:-0.22f,weirdness:0.2f}}],type:"minecraft:multi_noise"},settings:"divinerpg:iceika",type:"minecraft:noise"},type:"divinerpg:iceika"}}
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?] {re:mixin}
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_246486_(WorldOpenFlows.java:164) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.WorldOpenFlowsMixin,pl:mixin:APP:terrablender.mixins.json:MixinWorldOpenFlows,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233122_(WorldOpenFlows.java:113) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.WorldOpenFlowsMixin,pl:mixin:APP:terrablender.mixins.json:MixinWorldOpenFlows,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.doLoadLevel(WorldOpenFlows.java:181) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.WorldOpenFlowsMixin,pl:mixin:APP:terrablender.mixins.json:MixinWorldOpenFlows,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233145_(WorldOpenFlows.java:169) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.WorldOpenFlowsMixin,pl:mixin:APP:terrablender.mixins.json:MixinWorldOpenFlows,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233133_(WorldOpenFlows.java:65) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.WorldOpenFlowsMixin,pl:mixin:APP:terrablender.mixins.json:MixinWorldOpenFlows,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101744_(WorldSelectionList.java:576) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_screen_skipped.WorldSelectionListMixin,pl:mixin:APP:obscure_api.mixins.json:client.WorldSelectionListMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101704_(WorldSelectionList.java:474) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_screen_skipped.WorldSelectionListMixin,pl:mixin:APP:obscure_api.mixins.json:client.WorldSelectionListMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_6375_(WorldSelectionList.java:413) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_screen_skipped.WorldSelectionListMixin,pl:mixin:APP:obscure_api.mixins.json:client.WorldSelectionListMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.components.AbstractSelectionList.m_6375_(AbstractSelectionList.java:298) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:38) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:92) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:balm.mixins.json:MouseHandlerAccessor,pl:mixin:APP:creativecore.mixins.json:MouseHandlerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:437) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:balm.mixins.json:MouseHandlerAccessor,pl:mixin:APP:creativecore.mixins.json:MouseHandlerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:189) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:balm.mixins.json:MouseHandlerAccessor,pl:mixin:APP:creativecore.mixins.json:MouseHandlerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:188) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:balm.mixins.json:MouseHandlerAccessor,pl:mixin:APP:creativecore.mixins.json:MouseHandlerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%23141!/:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23153!/:build 7] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23141!/:build 7] {re:mixin}
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.json:MixinGlStateManager,pl:mixin:APP:mixins.oculus.json:MixinRenderSystem,pl:mixin:APP:mixins.oculus.json:statelisteners.MixinRenderSystem,pl:mixin:A}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.json:MixinGlStateManager,pl:mixin:APP:mixins.oculus.json:MixinRenderSystem,pl:mixin:APP:mixins.oculus.json:statelisteners.MixinRenderSystem,pl:mixin:A}
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:274) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1170) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:mixin:APP:mixins.hammerlib.json:client.MinecraftMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Images,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:mixin:APP:mixins.hammerlib.json:client.MinecraftMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Images,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-47.1.47.jar:47.1] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114) ~[loader-47.1.47.jar:47.1] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-47.1.47.jar:47.1] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-47.1.47.jar:47.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
Caused by: java.lang.RuntimeException: No key preset in MapLike[{biomes:[{biome:"divinerpg:frozen_peaks",parameters:{continentalness:0.8f,depth:-0.2f,erosion:-0.2f,humidity:-0.2f,offset:0.0f,temperature:-0.6f,weirdness:-0.6f}},{biome:"divinerpg:snowy_peaks",parameters:{continentalness:1.0f,depth:-0.1f,erosion:-0.1f,humidity:-0.1f,offset:0.0f,temperature:0.6f,weirdness:0.0f}},{biome:"divinerpg:taiga",parameters:{continentalness:0.6f,depth:0.43f,erosion:0.43f,humidity:0.43f,offset:0.0f,temperature:0.6f,weirdness:0.0f}},{biome:"divinerpg:ice_spikes",parameters:{continentalness:0.1f,depth:0.49f,erosion:0.49f,humidity:0.49f,offset:0.3f,temperature:-0.8f,weirdness:0.6f}},{biome:"divinerpg:tundra",parameters:{continentalness:0.2f,depth:0.48f,erosion:0.48f,humidity:0.48f,offset:0.1f,temperature:0.1f,weirdness:-0.2f}},{biome:"divinerpg:frozen_ocean",parameters:{continentalness:-0.35f,depth:0.6f,erosion:0.6f,humidity:0.6f,offset:0.0f,temperature:0.0f,weirdness:0.0f}},{biome:"divinerpg:deep_frozen_ocean",parameters:{continentalness:-0.5f,depth:0.6f,erosion:0.6f,humidity:0.6f,offset:0.0f,temperature:0.0f,weirdness:0.0f}},{biome:"divinerpg:thermal_vents",parameters:{continentalness:-0.87f,depth:0.85f,erosion:0.85f,humidity:0.85f,offset:0.0f,temperature:0.1f,weirdness:0.0f}},{biome:"divinerpg:boneyard",parameters:{continentalness:-0.75f,depth:0.68f,erosion:0.68f,humidity:0.68f,offset:0.0f,temperature:-0.22f,weirdness:0.2f}}],type:"minecraft:multi_noise"}] missed input: {"divinerpg:iceika":{generator:{biome_source:{biomes:[{biome:"divinerpg:frozen_peaks",parameters:{continentalness:0.8f,depth:-0.2f,erosion:-0.2f,humidity:-0.2f,offset:0.0f,temperature:-0.6f,weirdness:-0.6f}},{biome:"divinerpg:snowy_peaks",parameters:{continentalness:1.0f,depth:-0.1f,erosion:-0.1f,humidity:-0.1f,offset:0.0f,temperature:0.6f,weirdness:0.0f}},{biome:"divinerpg:taiga",parameters:{continentalness:0.6f,depth:0.43f,erosion:0.43f,humidity:0.43f,offset:0.0f,temperature:0.6f,weirdness:0.0f}},{biome:"divinerpg:ice_spikes",parameters:{continentalness:0.1f,depth:0.49f,erosion:0.49f,humidity:0.49f,offset:0.3f,temperature:-0.8f,weirdness:0.6f}},{biome:"divinerpg:tundra",parameters:{continentalness:0.2f,depth:0.48f,erosion:0.48f,humidity:0.48f,offset:0.1f,temperature:0.1f,weirdness:-0.2f}},{biome:"divinerpg:frozen_ocean",parameters:{continentalness:-0.35f,depth:0.6f,erosion:0.6f,humidity:0.6f,offset:0.0f,temperature:0.0f,weirdness:0.0f}},{biome:"divinerpg:deep_frozen_ocean",parameters:{continentalness:-0.5f,depth:0.6f,erosion:0.6f,humidity:0.6f,offset:0.0f,temperature:0.0f,weirdness:0.0f}},{biome:"divinerpg:thermal_vents",parameters:{continentalness:-0.87f,depth:0.85f,erosion:0.85f,humidity:0.85f,offset:0.0f,temperature:0.1f,weirdness:0.0f}},{biome:"divinerpg:boneyard",parameters:{continentalness:-0.75f,depth:0.68f,erosion:0.68f,humidity:0.68f,offset:0.0f,temperature:-0.22f,weirdness:0.2f}}],type:"minecraft:multi_noise"},settings:"divinerpg:iceika",type:"minecraft:noise"},type:"divinerpg:iceika"}}
	at com.mojang.serialization.DataResult.lambda$getOrThrow$5(DataResult.java:101) ~[datafixerupper-6.0.8.jar%23114!/:?] {}
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[datafixerupper-6.0.8.jar%23114!/:?] {}
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93) ~[datafixerupper-6.0.8.jar%23114!/:?] {}
	at net.minecraft.world.level.storage.LevelStorageSource.m_264027_(LevelStorageSource.java:244) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:classloading}
	at net.minecraft.world.level.storage.LevelStorageSource.m_230817_(LevelStorageSource.java:202) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:classloading}
	at net.minecraft.world.level.storage.LevelStorageSource$LevelStorageAccess.m_246049_(LevelStorageSource.java:439) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,xf:fml:xaeroworldmap:xaero_wm_levelstorageaccess_deletelevel,xf:fml:xaerominimap:xaero_levelstorageaccess_deletelevel,re:classloading,xf:fml:xaeroworldmap:xaero_wm_levelstorageaccess_deletelevel,xf:fml:xaerominimap:xaero_levelstorageaccess_deletelevel}
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_244698_(WorldOpenFlows.java:116) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.WorldOpenFlowsMixin,pl:mixin:APP:terrablender.mixins.json:MixinWorldOpenFlows,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.WorldLoader.m_214362_(WorldLoader.java:35) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:classloading}
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_246486_(WorldOpenFlows.java:162) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.WorldOpenFlowsMixin,pl:mixin:APP:terrablender.mixins.json:MixinWorldOpenFlows,pl:mixin:A,pl:runtimedistcleaner:A}
	... 40 more
[19:00:02] [Render thread/INFO] [minecraft/Minecraft]: Stopping!

**Comment by NicosaurusRex99** [comment]
Probably the same as #604 but on a server you may need to delete level.dat_old aswell

**Comment by uhloin** [comment]
Thank you. Instruction from #604 did not work until I remove whOle entry 
level.dat/worldgensettings/dimensions/divinerpg:iceika
After quit-load it was re-created like
level.dat/worldgensettings/dimensions/divinerpg/iceika

**Comment by NicosaurusRex99** [comment]
So you got it working?

**Comment by uhloin** [comment]
Yes, the game is loaded. Cannot say anything about iseika gameplay, not entered it yet.
