### ISSUE TITLE
Gem Fin mob has a duplicate entity id value of 21 (With modpack in 1.20.1)

### ISSUE THREAD

**Issue by RealMichaelDino** [DivineRPG/DivineRPG#690]
Hallo!
So, running into an odd issue here, whenever I try to create a world with my massive modpack of ~600 mods (some with sinytra connector, however it is based on forge) I enter the world but then it kicks me out for invalid player data, with a common root seaming to point at the Gem Fin having a duplicate entity id value of 21.
Once I get crashed out however I can reload the world and enter and play in it as normal, however the Gem Fin cannot be summoned due to its duplicate entity id.
If it helps I will post a latest.log
If an solution can be found or at least the other mod that could be conflicting can be indentified that would be amazing!
Thanks!
[latest.log](https://github.com/user-attachments/files/18000976/latest.log)
(Also if any further info is needed feel free to ask)

**Comment by RealMichaelDino** [comment]
UPDATE
Actually found the mod causing the conflict, apparently it was bucketlib!
Unfortunately had to remove simpleores as a result.
If there's anything else though to note, everything is appreciated!

**Comment by NicosaurusRex99** [comment]
net.mcreator.raxiores

it would appear thsat this mcreator mod also has issues

**Comment by RealMichaelDino** [comment]
> net.mcreator.raxiores
> 
> it would appear thsat this mcreator mod also has issues

Interesting, I haven't noticed any issues with the mod (it just adds a few dinosaurs) myself whilst in game, but at the same time I'm not someone who is super-familiar with creating mods so I wouldn't probably notice the errors without diving into the mess of code that can be debug logs and stuff! How ever if it's a mod that could be causing some issues then that is definitely some helpful insight, thanks!

**Comment by NicosaurusRex99** [comment]
Im not particularly sure whats going on but it seems like there is an issue with a command that mod has.
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.getPersistentData()" because the return value of "net.mcreator.raxiores.procedures.DistanceProcedure$1.getEntity()" is null
	at net.mcreator.raxiores.procedures.DistanceProcedure.execute(DistanceProcedure.java:22) ~[Raxiores-2.0-1.20.1.jar%231152!/:?]
	at net.mcreator.raxiores.command.RaxioresmanageCommand.lambda$registerCommand$2(RaxioresmanageCommand.java:70) ~[Raxiores-2.0-1.20.1.jar%231152!/:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.1.8.jar%23113!/:?]
	at net.minecraft.commands.Commands.m_242674_(Commands.java:257) ~[client-1.20.1-20230612.114412-srg.jar%231284!/:?]
	at net.minecraft.commands.Commands.m_230957_(Commands.java:237) ~[client-1.20.1-20230612.114412-srg.jar%231284!/:?]
	at net.mcreator.raxiores.procedures.TrexTargetedProcedure.execute(TrexTargetedProcedure.java:54) ~[Raxiores-2.0-1.20.1.jar%231152!/:?]
	at net.mcreator.raxiores.procedures.TrexTargetedProcedure.onEntitySetsAttackTarget(TrexTargetedProcedure.java:26) ~[Raxiores-2.0-1.20.1.jar%231152!/:?]
	at net.mcreator.raxiores.procedures.__TrexTargetedProcedure_onEntitySetsAttackTarget_LivingChangeTargetEvent.invoke(.dynamic) ~[Raxiores-2.0-1.20.1.jar%231152!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.common.ForgeHooks.onLivingChangeTarget(ForgeHooks.java:249) ~[forge-1.20.1-47.3.0-universal.jar%231289!/:?]
	at net.minecraft.world.entity.Mob.m_6710_(Mob.java:235) ~[client-1.20.1-20230612.114412-srg.jar%231284!/:?]
	at divinerpg.entities.vanilla.overworld.EntityPumpkinSpider.setProvoked(EntityPumpkinSpider.java:74) ~[divinerpg-1.10.7.5.jar%23933!/:1.10.7.5]
	at divinerpg.entities.vanilla.overworld.EntityPumpkinSpider.m_8119_(EntityPumpkinSpider.java:46) ~[divinerpg-1.10.7.5.jar%23933!/:1.10.7.5]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[client-1.20.1-20230612.114412-srg.jar%231284!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%231284!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%231284!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%231284!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%231284!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%231284!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%231284!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%231284!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%231284!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%231284!/:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
	```

**Comment by velocityraptor-real** [comment]
As a rule, MCreator mods are likely to be erroneous by experience. This is because those mods are created with a tool and do not require much modding expertise to work with. So it is easy to have someone inexperienced with modding creating something prone to errors.

**Comment by RealMichaelDino** [comment]
Did some research for myself and looks like yeah mcreator mods don't seem to be as well optimized(especially if made by someone with little experience) combine that with a modpack with give or take ~500 mods I guess that provided many opportunities to cause problems like this one!
Thanks for the quick help and insights though, appreciated!

**Comment by Moses24713** [comment]
Wasn't sure if it was worth opening a new issue but I had same problem with duplicate id for aequorea when using [KubeJS Iron's Spells](https://modrinth.com/mod/isskjs).
Thought I should leave this here in case someone else runs into this
