### ISSUE TITLE
Cannot start a server with DivineRPG Mod (SERVER CRASH)

### ISSUE THREAD

**Issue by NHrebeniuk** [DivineRPG/DivineRPG#697]
Greetings!

Having a following issue with mod loading. Can somebody help me please?

Thank you!

====================================================================================

```
-- Head --
Thread: main
Stacktrace:
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.common.asm.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:60) ~[loader-4.0.34.jar%2360!/:4.0] {}
-- Mod loading issue for: divinerpg --
Details:
	Caused by 0: java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class divinerpg/events/ArcanaRenderer for invalid dist DEDICATED_SERVER
		at TRANSFORMER/divinerpg@1.10.8/divinerpg.DivineRPG.<init>(DivineRPG.java:56) ~[divinerpg-1.10.8.jar%23374!/:?] {re:classloading}
		at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?] {}
		at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?] {}
		at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?] {}
		at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:115) ~[loader-4.0.34.jar%2360!/:4.0] {}
		at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModLoader.lambda$constructMods$3(ModLoader.java:153) ~[loader-4.0.34.jar%2360!/:4.0] {}
		at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:231) ~[loader-4.0.34.jar%2360!/:4.0] {}
		at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?] {re:mixin}
		at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[?:?] {}
		at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?] {}
		at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507) ~[?:?] {}
		at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1489) ~[?:?] {}
		at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2071) ~[?:?] {re:mixin,re:computing_frames}
		at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2033) ~[?:?] {re:mixin,re:computing_frames}
		at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187) ~[?:?] {re:mixin}

	Mod file: /home/container/mods/divinerpg-1.10.8.jar
	Failure message: DivineRPG (divinerpg) has failed to load correctly
		java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class divinerpg/events/ArcanaRenderer for invalid dist DEDICATED_SERVER
	Mod version: 1.10.8
	Mod issues URL: https://github.com/DivineRPG/DivineRPG/issues
	Exception message: java.lang.RuntimeException: Attempted to load class divinerpg/events/ArcanaRenderer for invalid dist DEDICATED_SERVER
Stacktrace:
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.common.asm.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:60) ~[loader-4.0.34.jar%2360!/:4.0] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:94) ~[modlauncher-11.0.4.jar%2362!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-11.0.4.jar%2362!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:57) ~[modlauncher-11.0.4.jar%2362!/:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:190) ~[securejarhandler-3.0.8.jar:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:311) ~[securejarhandler-3.0.8.jar:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?] {}
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:214) ~[securejarhandler-3.0.8.jar:?] {}
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at TRANSFORMER/divinerpg@1.10.8/divinerpg.DivineRPG.<init>(DivineRPG.java:56) ~[divinerpg-1.10.8.jar%23374!/:?] {re:classloading}
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?] {}
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?] {}
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:115) ~[loader-4.0.34.jar%2360!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModLoader.lambda$constructMods$3(ModLoader.java:153) ~[loader-4.0.34.jar%2360!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:231) ~[loader-4.0.34.jar%2360!/:4.0] {}
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?] {re:mixin}
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[?:?] {}
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1489) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2071) ~[?:?] {re:mixin,re:computing_frames}
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2033) ~[?:?] {re:mixin,re:computing_frames}
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187) ~[?:?] {re:mixin}
```

**Comment by NicosaurusRex99** [comment]
Same as #696
Will fix asap
